### PR TITLE
support boolean column as deleted field

### PR DESCRIPTION
**Pull request by Jack-An**

### CODE REVIEW

**Comment by flipbit03** [comment]
I like this idea, but I supposed we'd need to flesh it out further. Your implementation seems 'bolted on' to solve your use case but has some shortcomings that we can improve on:

- If we use the `is_bool_flag` to compare against `False` for the boolean case, we'll still be missing the `None` (NULL) case which ALSO should mean "NOT softdeleted", so we should at least have an `or_(` there comparing for both `False` and `None`

- We don't currently have the capability to make the soft-deleted Column type not-null, so I believe we should break the API and break out the `deleted_column_type` into a full blown `deleted_column_field` so that we can pass in a full assembled `Column` object. That would allow us to do things like `deleted_column_field = Column(Boolean, nullable=False, default=False)` so that you can specify these other important arguments.

I believe that with these changes, the `is_bool` flag also becomes completely unnecessary since we can inspect that Column object to check
- The TYPE it should have
  - and inside the library, we can have an automatic edge case that detects a `Boolean` inside the column and does the work for your instead of having to specify it two times with `deleted_column_type` and `is_bool`...

Does this feedback make sense to you? Thank you for your time and interest in the library.

**Comment by Jack-An** [comment]
Your idea is good, I make this PR just make boo column work, not think about enough. if you have time to implement this idea,  the project will be more convinient for use.

**Comment by flipbit03** [comment]
@Jack-An unfortunately, my time is very limited and I'm tailoring the library for my current use case, which is datetime. I would more than welcome a well groomed PR if you are up to the task, since this is open source stuff :-) Thanks

**Comment by flipbit03** [comment]
[stale]

**Pull request closed without merging**
